class HomePageSelector:
    DAY_PICKER = '[data-test="DayDateTypography"]'
    NEXT_MONTH = 'button[data-test="CalendarMoveNextButton"]'
    SEARCH_BUTTON = 'a[data-test="LandingSearchButton"]'
    ACCOMMODATION_CHECKBOX = '[data-test="bookingCheckbox"]'
    DATE_PICKER_INPUT = '[data-test="SearchFieldDateInput"]'
    RETURN_PICKER = '[data-test="SearchFormModesPicker-active-return"]'
    ONE_WAY_TRIP_OPTION = '[data-test="ModePopupOption-oneWay"]'
    RETURN_TRIP_OPTION = '[data-test="ModePopupOption-return"]'
    DEPARTURE_PICKER = '[data-test="PlacePickerInput-origin"]'
    DESTINATION_PICKER = '[data-test="PlacePickerInput-destination"]'
    DEPARTURE_INPUT = '[data-test="PlacePickerInput-origin"] input'
    DEPARTURE_OPTION = '[data-test="PlacePickerRow-city"]'
    DESTINATION_INPUT = '[data-test="PlacePickerInput-destination"] input'
    MONTH_BUTTON = 'button[data-test="DatepickerMonthButton"]'
    SELECTED_DATE = '[data-test="DateValue"]'
    CALENDAR_DAY = '[data-test="CalendarDay"]{}'
    SET_DATES = 'button[data-test="SearchFormDoneButton"]'
